//------------------------------------------------------------------------------
// Copyright (c) 2005, 2006 IBM Corporation and others.
// All rights reserved. This program and the accompanying materials
// are made available under the terms of the Eclipse Public License v1.0
// which accompanies this distribution, and is available at
// http://www.eclipse.org/legal/epl-v10.html
// 
// Contributors:
// IBM Corporation - initial implementation
//------------------------------------------------------------------------------

// This file will include dynamically generated process layout related data from 
// the publishing service 
contentPage.processPage.imageFiles["_y-eg0QusEe-KNZeel9MAgAActivity"]="./../../Business Model/capabilitypatterns/resources/Asses Bussines Status_659D75D9_659d75d9_Activity.jpeg"
contentPage.processPage.imageFiles["_zAmDMQ86Ee-XRJQJ8FX8UgActivity"]="./../../Business Model/capabilitypatterns/resources/Identify Business Processes_34F2567B_34f2567b_Activity.jpeg"
contentPage.processPage.imageFiles["_IJG5UQ_QEe-XRJQJ8FX8UgActivity"]="./../../Business Model/capabilitypatterns/resources/Describe Current Business_73A4C5F8_73a4c5f8_Activity.jpeg"
contentPage.processPage.imageFiles["_lHzgcQ_UEe-XRJQJ8FX8UgActivity"]="./../../Business Model/capabilitypatterns/resources/Refine Business Process Definitions_36A83208_36a83208_Activity.jpeg"
contentPage.processPage.imageFiles["_92IhwQ_cEe-XRJQJ8FX8UgActivity"]="./../../Business Model/capabilitypatterns/resources/Explore Process Automation_11F4BED1_11f4bed1_Activity.jpeg"
contentPage.processPage.imageFiles["_sJwfQQ_fEe-XRJQJ8FX8UgActivity"]="./../../Business Model/capabilitypatterns/resources/Design Business Process Realizations_9E427AA8_9e427aa8_Activity.jpeg"
contentPage.processPage.imageFiles["_BcqmwQ_hEe-XRJQJ8FX8UgActivity"]="./../../Business Model/capabilitypatterns/resources/Refine Roles and Responsibilities_2CD5C6FB_2cd5c6fb_Activity.jpeg"
contentPage.processPage.imageFiles["_P3BkAQuuEe-KNZeel9MAgA,_BQXtoQ_VEe-XRJQJ8FX8UgActivity"]="./../../Business Model/deliveryprocesses/resources/Refine Business Process Definitions_D4F2B75F_ce03a9b3_Activity.jpeg"
contentPage.processPage.imageFiles["_P3BkAQuuEe-KNZeel9MAgA,_Tyt9gQuuEe-KNZeel9MAgAActivity"]="./../../Business Model/deliveryprocesses/resources/Asses Bussines Status_3E9EC738_37afb98c_Activity.jpeg"
contentPage.processPage.imageFiles["_P3BkAQuuEe-KNZeel9MAgA,_MsSWUQ_gEe-XRJQJ8FX8UgActivity"]="./../../Business Model/deliveryprocesses/resources/Design Business Process Realizations_774D2BC9_705e1e1d_Activity.jpeg"
contentPage.processPage.imageFiles["_P3BkAQuuEe-KNZeel9MAgA,_IsNTcQ_dEe-XRJQJ8FX8UgActivity"]="./../../Business Model/deliveryprocesses/resources/Explore Process Automation_20760B1E_1986fd72_Activity.jpeg"
contentPage.processPage.imageFiles["_P3BkAQuuEe-KNZeel9MAgA,_sZZGcQ_OEe-XRJQJ8FX8UgActivity"]="./../../Business Model/deliveryprocesses/resources/Identify Business Processes_2660DED_fb770041_Activity.jpeg"
contentPage.processPage.imageFiles["_P3BkAQuuEe-KNZeel9MAgA,_O59SUA_hEe-XRJQJ8FX8UgActivity"]="./../../Business Model/deliveryprocesses/resources/Refine Roles and Responsibilities_9716950_2825ba4_Activity.jpeg"
contentPage.processPage.imageFiles["_P3BkAQuuEe-KNZeel9MAgAActivity"]="./../../Business Model/deliveryprocesses/resources/Process_72B86400_72b86400_Activity.jpeg"
contentPage.processPage.imageFiles["_P3BkAQuuEe-KNZeel9MAgA,_RhwjYQ_TEe-XRJQJ8FX8UgActivity"]="./../../Business Model/deliveryprocesses/resources/Describe Current Business_CABD50B1_c3ce4305_Activity.jpeg"
contentPage.processPage.elementUrls["_N6NukA_LEe-XRJQJ8FX8Ug"] = ["Define the Business Architecture","Business Model/tasks/define_the_business_architecture_EBCC75FA.html"];
contentPage.processPage.elementUrls["_z6c0Yw_fEe-XRJQJ8FX8Ug"] = ["Busines Vision","Business Model/workproducts/busines_vision_9DE24BD0.html"];
contentPage.processPage.elementUrls["_UIcycw_LEe-XRJQJ8FX8Ug"] = ["Glossary","Business Model/workproducts/glossary_72A5DF5C.html"];
contentPage.processPage.elementUrls["_6IyycAusEe-KNZeel9MAgA"] = ["Capture a Common Business Vocabulary","Business Model/tasks/capture_a_common_business_vocabulary_5E82697C.html"];
contentPage.processPage.elementUrls["_Gq4_IQ_hEe-XRJQJ8FX8Ug"] = ["Business Designer","Business Model/roles/business_designer_1BB32897.html"];
contentPage.processPage.elementUrls["_5bC7oQusEe-KNZeel9MAgA"] = ["Business_Process_Analyst","Business Model/roles/business_process_analyst_828E60AA.html"];
contentPage.processPage.elementUrls["_Ad8RgQ_dEe-XRJQJ8FX8Ug"] = ["Business_Process_Analyst","Business Model/roles/business_process_analyst_828E60AA.html"];
contentPage.processPage.elementUrls["_rP_R4g5vEe-uEvymC0p-sg"] = ["Vision","Business Model/workproducts/vision_6312DC7.html"];
contentPage.processPage.elementUrls["_QmcSDQ_QEe-XRJQJ8FX8Ug"] = ["Business Use Case","Business Model/workproducts/business_use_case_A09C065E.html"];
contentPage.processPage.elementUrls["_QmcSCw_QEe-XRJQJ8FX8Ug"] = ["Supplementary Business Specification","Business Model/workproducts/supplementary_business_specification_DF2239E9.html"];
contentPage.processPage.elementUrls["_UE7LFQ_QEe-XRJQJ8FX8Ug"] = ["Business Object Model","Business Model/workproducts/business_object_model_A9A40639.html"];
contentPage.processPage.elementUrls["_Gq4_Iw_hEe-XRJQJ8FX8Ug"] = ["Business Modeling Guidelines","Business Model/workproducts/business_modeling_guidelines_9427EA38.html"];
contentPage.processPage.elementUrls["_vosEUw_fEe-XRJQJ8FX8Ug"] = ["Business Use-Case Realization","Business Model/workproducts/business_use-case_realization_13FB3B30.html"];
contentPage.processPage.elementUrls["_IJG5UQ_QEe-XRJQJ8FX8Ug"] = ["Describe Current Business","Business Model/capabilitypatterns/Describe Current Business_73A4C5F8.html"];
contentPage.processPage.elementUrls["_BcqmwQ_hEe-XRJQJ8FX8Ug"] = ["Refine Roles and Responsibilities","Business Model/capabilitypatterns/Refine Roles and Responsibilities_2CD5C6FB.html"];
contentPage.processPage.elementUrls["_vosEQA_fEe-XRJQJ8FX8Ug"] = ["Find Business Workers and Entities","Business Model/tasks/find_business_workers_and_entities_BA0E92CA.html"];
contentPage.processPage.elementUrls["_Jaaicg_LEe-XRJQJ8FX8Ug"] = ["Business Architecture Document","Business Model/workproducts/business_architecture_document_E60CEC6B.html"];
contentPage.processPage.elementUrls["_vosESQ_fEe-XRJQJ8FX8Ug"] = ["Business Modeling Guidelines","Business Model/workproducts/business_modeling_guidelines_9427EA38.html"];
contentPage.processPage.elementUrls["_Ad8RhQ_dEe-XRJQJ8FX8Ug"] = ["Busines Vision","Business Model/workproducts/busines_vision_9DE24BD0.html"];
contentPage.processPage.elementUrls["_C_MGQQ_dEe-XRJQJ8FX8Ug"] = ["Business Designer","Business Model/roles/business_designer_1BB32897.html"];
contentPage.processPage.elementUrls["_6UffoA_fEe-XRJQJ8FX8Ug"] = ["Define the Business Architecture","Business Model/tasks/define_the_business_architecture_EBCC75FA.html"];
contentPage.processPage.elementUrls["_6IyycQusEe-KNZeel9MAgA"] = ["Busines Vision","Business Model/workproducts/busines_vision_9DE24BD0.html"];
contentPage.processPage.elementUrls["_6uWWkwusEe-KNZeel9MAgA"] = ["Business Object Model","Business Model/workproducts/business_object_model_A9A40639.html"];
contentPage.processPage.elementUrls["_sw_fYw_UEe-XRJQJ8FX8Ug"] = ["Review Record","Business Model/workproducts/review_record_96E05876.html"];
contentPage.processPage.elementUrls["_Q3CFAw_LEe-XRJQJ8FX8Ug"] = ["Stakeholder Requests","Business Model/workproducts/stakeholder_requests_1C6F694E.html"];
contentPage.processPage.elementUrls["_vosEUQ_fEe-XRJQJ8FX8Ug"] = ["Business Worker","Business Model/workproducts/business_worker_129B7A41.html"];
contentPage.processPage.elementUrls["_UE7LFw_QEe-XRJQJ8FX8Ug"] = ["Business Entity","Business Model/workproducts/business_entity_E4538203.html"];
contentPage.processPage.elementUrls["_vosETw_fEe-XRJQJ8FX8Ug"] = ["Business Entity","Business Model/workproducts/business_entity_E4538203.html"];
contentPage.processPage.elementUrls["_p_dy-Q_UEe-XRJQJ8FX8Ug"] = ["Business Use-Case Model","Business Model/workproducts/business_use-case_model_FA8D1A69.html"];
contentPage.processPage.elementUrls["_C_MGRQ_dEe-XRJQJ8FX8Ug"] = ["Supplementary Business Specification","Business Model/workproducts/supplementary_business_specification_DF2239E9.html"];
contentPage.processPage.elementUrls["_Gq4_IA_hEe-XRJQJ8FX8Ug"] = ["Detail a Business Worker","Business Model/tasks/detail_a_business_worker_D3B4087E.html"];
contentPage.processPage.elementUrls["_KWJv8A_hEe-XRJQJ8FX8Ug"] = ["Review the Business Object Model","Business Model/tasks/review_the_business_object_model_51325CFB.html"];
contentPage.processPage.elementUrls["_Gq4_LQ_hEe-XRJQJ8FX8Ug"] = ["Business Worker","Business Model/workproducts/business_worker_129B7A41.html"];
contentPage.processPage.elementUrls["_zAmDMQ86Ee-XRJQJ8FX8Ug"] = ["Identify Business Processes","Business Model/capabilitypatterns/Identify Business Processes_34F2567B.html"];
contentPage.processPage.elementUrls["_92IhwQ_cEe-XRJQJ8FX8Ug"] = ["Explore Process Automation","Business Model/capabilitypatterns/Explore Process Automation_11F4BED1.html"];
contentPage.processPage.elementUrls["_QmcSCQ_QEe-XRJQJ8FX8Ug"] = ["Business Use-Case Model","Business Model/workproducts/business_use-case_model_FA8D1A69.html"];
contentPage.processPage.elementUrls["_UE7LEQ_QEe-XRJQJ8FX8Ug"] = ["Business Designer","Business Model/roles/business_designer_1BB32897.html"];
contentPage.processPage.elementUrls["_MolVUA_QEe-XRJQJ8FX8Ug"] = ["Assess Target Organization","Business Model/tasks/assess_target_organization_2725BA2E.html"];
contentPage.processPage.elementUrls["_y-eg0QusEe-KNZeel9MAgA"] = ["Asses Bussines Status","Business Model/capabilitypatterns/Asses Bussines Status_659D75D9.html"];
contentPage.processPage.elementUrls["_JBDlQA_hEe-XRJQJ8FX8Ug"] = ["Detail a Business Entity","Business Model/tasks/detail_a_business_entity_CBBBCAF6.html"];
contentPage.processPage.elementUrls["_7JKqUAusEe-KNZeel9MAgA"] = ["Set and Ajust Goals","Business Model/tasks/set_and_ajust_goals_EB784BA7.html"];
contentPage.processPage.elementUrls["_vosERw_fEe-XRJQJ8FX8Ug"] = ["Supplementary Business Specification","Business Model/workproducts/supplementary_business_specification_DF2239E9.html"];
contentPage.processPage.elementUrls["_P3BkAQuuEe-KNZeel9MAgA"] = ["Process","Business Model/deliveryprocesses/Process_72B86400.html"];
contentPage.processPage.elementUrls["_MolVUQ_QEe-XRJQJ8FX8Ug"] = ["Business_Process_Analyst","Business Model/roles/business_process_analyst_828E60AA.html"];
contentPage.processPage.elementUrls["_JBDlQQ_hEe-XRJQJ8FX8Ug"] = ["Business Entity","Business Model/workproducts/business_entity_E4538203.html"];
contentPage.processPage.elementUrls["_BQXtoQ_VEe-XRJQJ8FX8Ug"] = ["Refine Business Process Definitions","Business Model/deliveryprocesses/Refine Business Process Definitions_D4F2B75F.html"];
contentPage.processPage.elementUrls["_Jaaieg_LEe-XRJQJ8FX8Ug"] = ["Business Use-Case Model","Business Model/workproducts/business_use-case_model_FA8D1A69.html"];
contentPage.processPage.elementUrls["_Q3CFAQ_LEe-XRJQJ8FX8Ug"] = ["Vision","Business Model/workproducts/vision_6312DC7.html"];
contentPage.processPage.elementUrls["_sw_fYQ_UEe-XRJQJ8FX8Ug"] = ["Business-Model Reviewer","Business Model/roles/business-model_reviewer_C12C9E7B.html"];
contentPage.processPage.elementUrls["_Kr70sA_LEe-XRJQJ8FX8Ug"] = ["Set and Ajust Goals","Business Model/tasks/set_and_ajust_goals_EB784BA7.html"];
contentPage.processPage.elementUrls["_p_dy8A_UEe-XRJQJ8FX8Ug"] = ["Structure the Business Use-Case Model","Business Model/tasks/structure_the_business_use-case_model_4C483E5D.html"];
contentPage.processPage.elementUrls["_rP2H8Q5vEe-uEvymC0p-sg"] = ["target_organization_assessment","Business Model/workproducts/target_organization_assessment_64F3E53.html"];
contentPage.processPage.elementUrls["_Gq4_JQ_hEe-XRJQJ8FX8Ug"] = ["Supplementary Business Specification","Business Model/workproducts/supplementary_business_specification_DF2239E9.html"];
contentPage.processPage.elementUrls["_sJwfQQ_fEe-XRJQJ8FX8Ug"] = ["Design Business Process Realizations","Business Model/capabilitypatterns/Design Business Process Realizations_9E427AA8.html"];
contentPage.processPage.elementUrls["_lHzgcQ_UEe-XRJQJ8FX8Ug"] = ["Refine Business Process Definitions","Business Model/capabilitypatterns/Refine Business Process Definitions_36A83208.html"];
contentPage.processPage.elementUrls["_KWJv8w_hEe-XRJQJ8FX8Ug"] = ["Business Glossary","Business Model/workproducts/business_glossary_AD48422C.html"];
contentPage.processPage.elementUrls["_JaQxcA_LEe-XRJQJ8FX8Ug"] = ["Maintain_Business_Rules","Business Model/tasks/maintain_business_rules_485A363F.html"];
contentPage.processPage.elementUrls["_p_dy-w_UEe-XRJQJ8FX8Ug"] = ["Business Use Case","Business Model/workproducts/business_use_case_A09C065E.html"];
contentPage.processPage.elementUrls["_6uWWlwusEe-KNZeel9MAgA"] = ["Business Use-Case Model","Business Model/workproducts/business_use-case_model_FA8D1A69.html"];
contentPage.processPage.elementUrls["_KWJv8Q_hEe-XRJQJ8FX8Ug"] = ["Business-Model Reviewer","Business Model/roles/business-model_reviewer_C12C9E7B.html"];
contentPage.processPage.elementUrls["_Kr70sQ_LEe-XRJQJ8FX8Ug"] = ["target_organization_assessment","Business Model/workproducts/target_organization_assessment_64F3E53.html"];
contentPage.processPage.elementUrls["_Ad8Rgw_dEe-XRJQJ8FX8Ug"] = ["target_organization_assessment","Business Model/workproducts/target_organization_assessment_64F3E53.html"];
contentPage.processPage.elementUrls["_3Sw0Aw_fEe-XRJQJ8FX8Ug"] = ["Business Rules","Business Model/workproducts/business_rules_CF23E573.html"];
contentPage.processPage.elementUrls["_z6c0YQ_fEe-XRJQJ8FX8Ug"] = ["Business_Process_Analyst","Business Model/roles/business_process_analyst_828E60AA.html"];
contentPage.processPage.elementUrls["_UE7LEA_QEe-XRJQJ8FX8Ug"] = ["Find Business Workers and Entities","Business Model/tasks/find_business_workers_and_entities_BA0E92CA.html"];
contentPage.processPage.elementUrls["_Gq4_Lw_hEe-XRJQJ8FX8Ug"] = ["Organization Unit","Business Model/workproducts/organization_unit_FBCBFE79.html"];
contentPage.processPage.elementUrls["_C_V3QA_dEe-XRJQJ8FX8Ug"] = ["[System]Use-Case Model","Business Model/workproducts/use-case_model_84D65400.html"];
contentPage.processPage.elementUrls["_QmcSAQ_QEe-XRJQJ8FX8Ug"] = ["Business Modeling Guidelines","Business Model/workproducts/business_modeling_guidelines_9427EA38.html"];
contentPage.processPage.elementUrls["_O59SUA_hEe-XRJQJ8FX8Ug"] = ["Refine Roles and Responsibilities","Business Model/deliveryprocesses/Refine Roles and Responsibilities_9716950.html"];
contentPage.processPage.elementUrls["_z6c0YA_fEe-XRJQJ8FX8Ug"] = ["Capture a Common Business Vocabulary","Business Model/tasks/capture_a_common_business_vocabulary_5E82697C.html"];
contentPage.processPage.elementUrls["_Gq4_Jw_hEe-XRJQJ8FX8Ug"] = ["Business Use-Case Realization","Business Model/workproducts/business_use-case_realization_13FB3B30.html"];
contentPage.processPage.elementUrls["_t1r2lw_UEe-XRJQJ8FX8Ug"] = ["Business Actor","Business Model/workproducts/business_actor_A033D0D7.html"];
contentPage.processPage.elementUrls["_5bC7oAusEe-KNZeel9MAgA"] = ["Assess Target Organization","Business Model/tasks/assess_target_organization_2725BA2E.html"];
contentPage.processPage.elementUrls["_QmcSAw_QEe-XRJQJ8FX8Ug"] = ["Stakeholder Requests","Business Model/workproducts/stakeholder_requests_1C6F694E.html"];
contentPage.processPage.elementUrls["_6IyycwusEe-KNZeel9MAgA"] = ["Business Glossary","Business Model/workproducts/business_glossary_AD48422C.html"];
contentPage.processPage.elementUrls["_p_dy9w_UEe-XRJQJ8FX8Ug"] = ["Business Modeling Guidelines","Business Model/workproducts/business_modeling_guidelines_9427EA38.html"];
contentPage.processPage.elementUrls["_UIcycA_LEe-XRJQJ8FX8Ug"] = ["Find Business Actors and Use Cases","Business Model/tasks/find_business_actors_and_use_cases_E3F5ED04.html"];
contentPage.processPage.elementUrls["_C_MGSQ_dEe-XRJQJ8FX8Ug"] = ["Business Glossary","Business Model/workproducts/business_glossary_AD48422C.html"];
contentPage.processPage.elementUrls["_Ad8RgA_dEe-XRJQJ8FX8Ug"] = ["Set and Ajust Goals","Business Model/tasks/set_and_ajust_goals_EB784BA7.html"];
contentPage.processPage.elementUrls["_Q3CFAA_LEe-XRJQJ8FX8Ug"] = ["Capture a Common Business Vocabulary","Business Model/tasks/capture_a_common_business_vocabulary_5E82697C.html"];
contentPage.processPage.elementUrls["_t1r2lQ_UEe-XRJQJ8FX8Ug"] = ["Stakeholder Requests","Business Model/workproducts/stakeholder_requests_1C6F694E.html"];
contentPage.processPage.elementUrls["_z6c0ZQ_fEe-XRJQJ8FX8Ug"] = ["Stakeholder Requests","Business Model/workproducts/stakeholder_requests_1C6F694E.html"];
contentPage.processPage.elementUrls["_vosEQQ_fEe-XRJQJ8FX8Ug"] = ["Business Designer","Business Model/roles/business_designer_1BB32897.html"];
contentPage.processPage.elementUrls["_UE7LGw_QEe-XRJQJ8FX8Ug"] = ["Business Use-Case Realization","Business Model/workproducts/business_use-case_realization_13FB3B30.html"];
contentPage.processPage.elementUrls["_C_MGRw_dEe-XRJQJ8FX8Ug"] = ["Business Object Model","Business Model/workproducts/business_object_model_A9A40639.html"];
contentPage.processPage.elementUrls["_Gq4_KQ_hEe-XRJQJ8FX8Ug"] = ["Business Use Case","Business Model/workproducts/business_use_case_A09C065E.html"];
contentPage.processPage.elementUrls["_Tyt9gQuuEe-KNZeel9MAgA"] = ["Asses Bussines Status","Business Model/deliveryprocesses/Asses Bussines Status_3E9EC738.html"];
contentPage.processPage.elementUrls["_C_MGTQ_dEe-XRJQJ8FX8Ug"] = ["Supplementary[System] Specifications","Business Model/workproducts/supplementary_specifications_93323B50.html"];
contentPage.processPage.elementUrls["_MsSWUQ_gEe-XRJQJ8FX8Ug"] = ["Design Business Process Realizations","Business Model/deliveryprocesses/Design Business Process Realizations_774D2BC9.html"];
contentPage.processPage.elementUrls["_6uWWkQusEe-KNZeel9MAgA"] = ["Business Architecture Document","Business Model/workproducts/business_architecture_document_E60CEC6B.html"];
contentPage.processPage.elementUrls["_C_MGQA_dEe-XRJQJ8FX8Ug"] = ["Define Automation Requirements","Business Model/tasks/define_automation_requirements_9BF1443E.html"];
contentPage.processPage.elementUrls["_3Sw0AQ_fEe-XRJQJ8FX8Ug"] = ["Business Architecture Document","Business Model/workproducts/business_architecture_document_E60CEC6B.html"];
contentPage.processPage.elementUrls["_p_dy9Q_UEe-XRJQJ8FX8Ug"] = ["Supplementary Business Specification","Business Model/workproducts/supplementary_business_specification_DF2239E9.html"];
contentPage.processPage.elementUrls["_6uWWmQusEe-KNZeel9MAgA"] = ["Business Rules","Business Model/workproducts/business_rules_CF23E573.html"];
contentPage.processPage.elementUrls["_UE7LEw_QEe-XRJQJ8FX8Ug"] = ["Business Glossary","Business Model/workproducts/business_glossary_AD48422C.html"];
contentPage.processPage.elementUrls["_C_V3Qg_dEe-XRJQJ8FX8Ug"] = ["Analysis Model","Business Model/workproducts/analysis_model_DCCAFF61.html"];
contentPage.processPage.elementUrls["_sZZGcQ_OEe-XRJQJ8FX8Ug"] = ["Identify Business Processes","Business Model/deliveryprocesses/Identify Business Processes_2660DED.html"];
contentPage.processPage.elementUrls["_QmcSDw_QEe-XRJQJ8FX8Ug"] = ["Business Actor","Business Model/workproducts/business_actor_A033D0D7.html"];
contentPage.processPage.elementUrls["_Gq4_Kw_hEe-XRJQJ8FX8Ug"] = ["Business Object Model","Business Model/workproducts/business_object_model_A9A40639.html"];
contentPage.processPage.elementUrls["_RhwjYQ_TEe-XRJQJ8FX8Ug"] = ["Describe Current Business","Business Model/deliveryprocesses/Describe Current Business_CABD50B1.html"];
contentPage.processPage.elementUrls["_UE7LGQ_QEe-XRJQJ8FX8Ug"] = ["Business Worker","Business Model/workproducts/business_worker_129B7A41.html"];
contentPage.processPage.elementUrls["_IsNTcQ_dEe-XRJQJ8FX8Ug"] = ["Explore Process Automation","Business Model/deliveryprocesses/Explore Process Automation_20760B1E.html"];
contentPage.processPage.elementUrls["_JaaidA_LEe-XRJQJ8FX8Ug"] = ["Business Object Model","Business Model/workproducts/business_object_model_A9A40639.html"];
contentPage.processPage.elementUrls["_rP_R5Q5vEe-uEvymC0p-sg"] = ["Stakeholder Requests","Business Model/workproducts/stakeholder_requests_1C6F694E.html"];
contentPage.processPage.elementUrls["_QmcSAA_QEe-XRJQJ8FX8Ug"] = ["Find Business Actors and Use Cases","Business Model/tasks/find_business_actors_and_use_cases_E3F5ED04.html"];
contentPage.processPage.elementUrls["_p_dy8w_UEe-XRJQJ8FX8Ug"] = ["Business Glossary","Business Model/workproducts/business_glossary_AD48422C.html"];
contentPage.processPage.elementUrls["_QmcSBw_QEe-XRJQJ8FX8Ug"] = ["Glossary","Business Model/workproducts/glossary_72A5DF5C.html"];
contentPage.processPage.elementUrls["_QmcSBQ_QEe-XRJQJ8FX8Ug"] = ["Vision","Business Model/workproducts/vision_6312DC7.html"];
contentPage.processPage.elementUrls["_JaaieA_LEe-XRJQJ8FX8Ug"] = ["Business Glossary","Business Model/workproducts/business_glossary_AD48422C.html"];
contentPage.processPage.elementUrls["_JaaifA_LEe-XRJQJ8FX8Ug"] = ["Busines Vision","Business Model/workproducts/busines_vision_9DE24BD0.html"];
contentPage.processPage.elementUrls["_JaaicA_LEe-XRJQJ8FX8Ug"] = ["Business_Process_Analyst","Business Model/roles/business_process_analyst_828E60AA.html"];
contentPage.processPage.elementUrls["_MolVUw_QEe-XRJQJ8FX8Ug"] = ["target_organization_assessment","Business Model/workproducts/target_organization_assessment_64F3E53.html"];
contentPage.processPage.elementUrls["_SPrgsQ_QEe-XRJQJ8FX8Ug"] = ["Busines Vision","Business Model/workproducts/busines_vision_9DE24BD0.html"];
contentPage.processPage.elementUrls["_3Sw0AA_fEe-XRJQJ8FX8Ug"] = ["Maintain_Business_Rules","Business Model/tasks/maintain_business_rules_485A363F.html"];
contentPage.processPage.elementUrls["_UIcydQ_LEe-XRJQJ8FX8Ug"] = ["Business Use Case","Business Model/workproducts/business_use_case_A09C065E.html"];
contentPage.processPage.elementUrls["_SPrgsA_QEe-XRJQJ8FX8Ug"] = ["Set and Ajust Goals","Business Model/tasks/set_and_ajust_goals_EB784BA7.html"];
contentPage.processPage.elementUrls["_t1r2kQ_UEe-XRJQJ8FX8Ug"] = ["Business Designer","Business Model/roles/business_designer_1BB32897.html"];
contentPage.processPage.elementUrls["_vosETQ_fEe-XRJQJ8FX8Ug"] = ["Business Object Model","Business Model/workproducts/business_object_model_A9A40639.html"];
contentPage.processPage.elementUrls["_Jaaidg_LEe-XRJQJ8FX8Ug"] = ["Supplementary Business Specification","Business Model/workproducts/supplementary_business_specification_DF2239E9.html"];
contentPage.processPage.elementUrls["_p_dy8Q_UEe-XRJQJ8FX8Ug"] = ["Business_Process_Analyst","Business Model/roles/business_process_analyst_828E60AA.html"];
contentPage.processPage.elementUrls["_C_MGSw_dEe-XRJQJ8FX8Ug"] = ["Business Architecture Document","Business Model/workproducts/business_architecture_document_E60CEC6B.html"];
contentPage.processPage.elementUrls["_6uWWkAusEe-KNZeel9MAgA"] = ["Maintain_Business_Rules","Business Model/tasks/maintain_business_rules_485A363F.html"];
contentPage.processPage.elementUrls["_vosESw_fEe-XRJQJ8FX8Ug"] = ["Business Glossary","Business Model/workproducts/business_glossary_AD48422C.html"];
contentPage.processPage.elementUrls["_t1r2kw_UEe-XRJQJ8FX8Ug"] = ["Vision","Business Model/workproducts/vision_6312DC7.html"];
contentPage.processPage.elementUrls["_vosERQ_fEe-XRJQJ8FX8Ug"] = ["Business Use-Case Model","Business Model/workproducts/business_use-case_model_FA8D1A69.html"];
contentPage.processPage.elementUrls["_KWJv9Q_hEe-XRJQJ8FX8Ug"] = ["Review Record","Business Model/workproducts/review_record_96E05876.html"];
contentPage.processPage.elementUrls["_sw_fYA_UEe-XRJQJ8FX8Ug"] = ["Review the Business Use-Case Model","Business Model/tasks/review_the_business_use-case_model_B60840CA.html"];
contentPage.processPage.elementUrls["_6uWWlQusEe-KNZeel9MAgA"] = ["Supplementary Business Specification","Business Model/workproducts/supplementary_business_specification_DF2239E9.html"];
contentPage.processPage.elementUrls["_C_MGQw_dEe-XRJQJ8FX8Ug"] = ["Business Use-Case Model","Business Model/workproducts/business_use-case_model_FA8D1A69.html"];
contentPage.processPage.elementUrls["_Jaaifg_LEe-XRJQJ8FX8Ug"] = ["Business Rules","Business Model/workproducts/business_rules_CF23E573.html"];
contentPage.processPage.elementUrls["_UIcydw_LEe-XRJQJ8FX8Ug"] = ["Business Actor","Business Model/workproducts/business_actor_A033D0D7.html"];
contentPage.processPage.elementUrls["_UIcycQ_LEe-XRJQJ8FX8Ug"] = ["Business Modeling Guidelines","Business Model/workproducts/business_modeling_guidelines_9427EA38.html"];
contentPage.processPage.elementUrls["_vosEQw_fEe-XRJQJ8FX8Ug"] = ["Vision","Business Model/workproducts/vision_6312DC7.html"];
contentPage.processPage.elementUrls["_t1r2kA_UEe-XRJQJ8FX8Ug"] = ["Detail a Business Use Case","Business Model/tasks/detail_a_business_use_case_EB20E1B1.html"];
